*** Variables ***
# chrome | firefox ==> c'est déjà déclaré dans le fichier Launch.json ou dans la ligne de commande de lancement
${BROWSER}
# fr | en ==> c'est déjà déclaré dans le fichier Launch.json ou dans la ligne de commande de lancement
${LANG}

${URL_IHM}    http://opencruise-ok.sogeti-center.cloud
${URL_IHM1}    https://digital-systems.innovation-factory.io/
${URL_IHM2}    https://lge-elit.innovation-factory.io/connexion
${URL_CONNEXION}    https://digital-systems.innovation-factory.io/login